---
abstract: 'A Module::Install extension to automatically convert POD to a README'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Capture::Tiny: 0.05
  ExtUtils::MakeMaker: 6.62
  File::Temp: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-ReadmeFromPod
no_index:
  directory:
    - inc
    - t
recommends:
  App::pod2pdf: 0
requires:
  Module::Install: 1
  Pod::Html: 0
  Pod::Man: 0
  Pod::Text: 3.13
  perl: 5.6.0
resources:
  homepage: https://github.com/bingos/module-install-readmefrompod/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/bingos/module-install-readmefrompod.git
    web: https://github.com/bingos/module-install-readmefrompod/tree
version: 0.16
