---
abstract: 'A Module::Install extension to automatically convert POD to a README'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Capture::Tiny: 0.05
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-ReadmeFromPod
no_index:
  directory:
    - inc
    - t
requires:
  Module::Install: 0.85
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/module-install-readmefrompod.git
version: 0.02
